version: '3.8'
name : bitcoin_miner_pool
networks:
  bitcoin_network:
    name: bitcoin_network
    driver: bridge

services:
  bitcoin_node:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoin_node
    command:
      - -regtest=1
      - -server=1
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -rpcuser=${RPC_USER}
      - -rpcpassword=${RPC_PASS}
      - -rpcport=18443
    ports:
      - "18443:18443"
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin
    networks:
      - bitcoin_network
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "-rpcuser=${RPC_USER}", "-rpcpassword=${RPC_PASS}", "getblockchaininfo"]
      interval: 10s
      timeout: 5s
      retries: 5

  bitcoin_pool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitcoin_pool
    ports:
      - "8765:8765"
    env_file:
      - .env
    environment:
      - RPC_URL=http://bitcoin_node:18443
      - RPC_USER=${RPC_USER}
      - RPC_PASS=${RPC_PASS}
      - MINER_PUBLIC_KEY=bcrt1qaj88xpedvteetelgnqy3h49mtl48p6l3n4g2t7
    depends_on:
      bitcoin_node:
        condition: service_healthy
    networks:
      - bitcoin_network

volumes:
  bitcoin_data: