# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make the start.sh script executable
RUN chmod +x start.sh


# Run start.sh when the container launches
ENTRYPOINT ["./start.sh"]


